<?php

/**
 * MedicineUserInfoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MedicineUserInfoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MedicineUserInfoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MedicineUserInfo');
    }
}