<?php

/**
 * MedicineDoctorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MedicineDoctorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MedicineDoctorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MedicineDoctor');
    }
}