<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/12/05 15:24:35

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=medicine',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
